#!/bin/bash

sed -i \
    -e "s#DESIGNATEDBS_ENV_MYSQL_USER#${DESIGNATEDBS_ENV_MYSQL_USER}#g" \
    -e "s#DESIGNATEDBS_ENV_MYSQL_PASSWORD#${DESIGNATEDBS_ENV_MYSQL_PASSWORD}#g" \
    -e "s#POWERDNSDBS_ENV_MYSQL_USER#${POWERDNSDBS_ENV_MYSQL_USER}#g" \
    -e "s#POWERDNSDBS_ENV_MYSQL_PASSWORD#${POWERDNSDBS_ENV_MYSQL_PASSWORD}#g" \
    /etc/designate.conf

designate-manage database sync
